import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import axios from "axios";
import moment from "moment";


const initialState = {
  loading: false,
  success: false,
  refreshSuccess: false,
  updateTime: null,
  error: "",
  cities: [],
  refreshedCities: null,
};



export const fetchData = createAsyncThunk(
  "fetchData",
  async (city, { rejectWithValue }) => {
    try {
      const response = await axios.post(
        "http://localhost:5000/weather/cityName",
        {
          cityName: city,
        }
      );
      return response.data.weather;
    } catch (err) {
      console.log(err);
      // Note: this is an example assuming the usage of axios. Other fetching libraries would likely have different implementations
      if (!err.response) {
        throw err;
      }

      return rejectWithValue(err.response.data);
    }
  }
);

export const refreshData = createAsyncThunk("refreshData", async (cityIds) => {
  const response = await axios.post("http://localhost:5000/weather/refresh", {
    cityIds,
  });
  return response.data.weather.list;
});

const weatherSlice = createSlice({
  name: "weather",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    deleteItem: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.cities.splice(action.payload, 1);
      // state.cities.slice(action.payload);
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder.addCase(fetchData.pending, (state, action) => {
      state.loading = true;
      state.success = false;
      state.error = "";
    });
    builder.addCase(fetchData.fulfilled, (state, action) => {
      state.loading = false;
      state.success = true;
      state.refreshSuccess = false;
      state.cities.push(action.payload);
    });
    builder.addCase(fetchData.rejected, (state, action) => {
      state.loading = false;
      if (action.payload) {
        // If a rejected action has a payload, it means that it was returned with rejectWithValue
        state.error = action.payload;
      } else {
        state.error = action.error;
      }
    });
    builder.addCase(refreshData.pending, (state, action) => {
      state.loading = true;
      state.refreshSuccess = false;
      state.error = "";
    });
    builder.addCase(refreshData.fulfilled, (state, action) => {
      state.loading = false;
      state.refreshSuccess = true;
      state.cities = action.payload;
      state.updateTime = moment().format('MMMM Do YYYY, h:mm:ss a');
    });
    builder.addCase(refreshData.rejected, (state, action) => {
      state.loading = false;
      state.error = "action.payload.error";
    });
  },
});

export const { deleteItem, deleteRefreshedItem } = weatherSlice.actions;

export default weatherSlice.reducer;
